import pandas as pd

# Example data containing comments and labels
data = [
    {"text": "I love this product! It's amazing!", "label": "positive"},
    {"text": "The customer service was terrible.", "label": "negative"},
    {"text": "Great experience with this company!", "label": "positive"},
    {"text": "The product arrived on time and works perfectly.", "label": "Positive"},
    {"text": "I'm not impressed with the customer service. They were unresponsive.", "label": "Negative"},
    {"text": "Great customer support! They quickly addressed my concerns.", "label": "Positive"},
    {"text": "The website is user-friendly and easy to navigate.", "label": "Positive"},
    {"text": "Worst purchase ever! The item was damaged, and the company refuses to refund.", "label": "Negative"},
    {"text": "Excellent quality and value for money.", "label": "Positive"},
    {"text": "This service exceeded my expectations. Highly recommended.", "label": "Positive"},
    {"text": "I regret buying from this company. Poor product quality.", "label": "Negative"},
    {"text": "The user interface needs improvement. It's not intuitive.", "label": "Negative"},
    {"text": "The delivery was prompt, and the packaging was secure.", "label": "Positive"},
    {"text": "The support team was helpful in resolving my issue.", "label": "Positive"},
    {"text": "I had a terrible experience with the delivery. It was delayed without explanation.", "label": "Negative"},
    {"text": "The product is just okay. Nothing special.", "label": "Neutral"},
    {"text": "Avoid this service. They overcharged me and provided no resolution.", "label": "Negative"},
    {"text": "Very satisfied with the product. It met all my expectations.", "label": "Positive"},
    {"text": "The worst service I've encountered. No one seems to care.", "label": "Negative"},
    {"text": "I love this new feature! It enhances the overall experience.", "label": "Positive"},
    {"text": "The quality of the product is subpar. Not worth the money.", "label": "Negative"},
    {"text": "The company provided a quick solution to my problem. Impressed!", "label": "Positive"},
    {"text": "This company is a scam. Beware of their deceptive practices.", "label": "Negative"},
    {"text": "The packaging was damaged, but the product is undamaged.", "label": "Neutral"},
    {"text": "The service was average. Nothing extraordinary.", "label": "Neutral"},
    {"text": "Quick response from customer support. They were attentive.", "label": "Positive"},
    {"text": "The worst experience ever! Terrible customer service and faulty product.", "label": "Negative"},
    {"text": "The product is fantastic, and the customer service is top-notch.", "label": "Positive"},
    {"text": "I had a neutral experience with this service. Neither good nor bad.", "label": "Neutral"},
    {"text": "Don't waste your money on this product. It's of poor quality.", "label": "Negative"},
    {"text": "Amazing customer service. They went above and beyond to help.", "label": "Positive"},
    {"text": "The website needs improvement. It's not intuitive and hard to navigate.", "label": "Negative"},
    {"text": "Satisfied with the purchase. Good value for the money.", "label": "Positive"},
    {"text": "I regret buying from this company. They provided no assistance.", "label": "Negative"},
    {"text": "Positive feedback for the outstanding product quality.", "label": "Positive"},
    {"text": "Service was subpar. The company failed to meet my expectations.", "label": "Negative"},
    {"text": "Impressed with the fast delivery. Good job!", "label": "Positive"},
    {"text": "Okay service, but the product didn't meet my expectations.", "label": "Neutral"},
    {"text": "Absolutely awful experience. Avoid at all costs.", "label": "Negative"},
    {"text": "The support team was unhelpful and seemed indifferent.", "label": "Negative"},
    {"text": "The product was delivered on time, but it's not what I expected.", "label": "Neutral"},
    {"text": "This company provides excellent customer service. Quick and efficient.", "label": "Positive"},
    {"text": "Negative experience with this service. Poor communication and support.", "label": "Negative"},
    {"text": "Very pleased with the purchase. Great product quality.", "label": "Positive"},
    {"text": "Avoid at all costs. Terrible service and products.", "label": "Negative"},
    {"text": "The delivery was delayed, and the product is not as described.", "label": "Negative"},
    {"text": "Impressed with the quality and durability of the product.", "label": "Positive"},
    {"text": "Service was below average. Not worth the money spent.", "label": "Negative"},
    {"text": "I love this product! It's amazing.", "label": "Positive"},
    {"text": "Terrible experience with this service. Will never use it again.", "label": "Negative"},
    {"text": "The customer support was very helpful. Thank you!", "label": "Positive"},
    {"text": "This is the worst purchase I've ever made. Completely disappointed.", "label": "Negative"},
    {"text": "The delivery was fast, and the product quality is excellent.", "label": "Positive"},
    {"text": "Had a great time using this service. Highly recommended!", "label": "Positive"},
    {"text": "Disappointed with the product. Not worth the money.", "label": "Negative"},
    {"text": "Quick response from customer support. Satisfied with the assistance.", "label": "Positive"},
    {"text": "The quality of the service is subpar. Would not recommend.", "label": "Negative"},
    {"text": "Impressed with the fast shipping and good packaging.", "label": "Positive"},
    {"text": "Another positive comment about the product.", "label": "Positive"},
    {"text": "The interface is user-friendly. Easy to navigate and use.", "label": "Positive"},
    {"text": "Negative experience with customer service. No resolution provided.", "label": "Negative"},
    {"text": "The product exceeded my expectations. I'm a happy customer.", "label": "Positive"},
    {"text": "Issues with the delivery. It took much longer than expected.", "label": "Negative"},
    {"text": "The worst customer service ever! No one knows how to help.", "label": "Negative"},
    {"text": "Highly dissatisfied with the quality. Regretting my purchase.", "label": "Negative"},
    {"text": "Positive feedback for the excellent customer support.", "label": "Positive"},
    {"text": "Average experience. Nothing extraordinary about the product.", "label": "Neutral"},
    {"text": "The packaging was damaged, and the product was not as described.", "label": "Negative"},
    {"text": "Love the new features! Great improvement.", "label": "Positive"},
    {"text": "Awful experience with this company. Will never buy again.", "label": "Negative"},
    {"text": "The product is fantastic. Highly recommend it to others.", "label": "Positive"},
    {"text": "Just okay. Nothing special about this service.", "label": "Neutral"},
    {"text": "I'm impressed with the customer service. Quick and helpful.", "label": "Positive"},
    {"text": "The worst product ever. Waste of money.", "label": "Negative"},
    {"text": "Another satisfied customer. The service exceeded my expectations.", "label": "Positive"},
    {"text": "Positive experience with this company. Will buy again.", "label": "Positive"},
    {"text": "Really enjoying the new update. Great improvements.", "label": "Positive"},
    {"text": "Absolutely horrible experience. Regret using this service.", "label": "Negative"},
    {"text": "The support team was quick to assist me. Very satisfied.", "label": "Positive"},
    {"text": "Waste of money. Product did not meet expectations.", "label": "Negative"},
    {"text": "The website is easy to use and navigate.", "label": "Positive"},
    {"text": "Never had such a terrible experience before. Disappointed.", "label": "Negative"},
    {"text": "Highly recommend this product. Exceeded my expectations.", "label": "Positive"},
    {"text": "Service was below par. Not worth the money.", "label": "Negative"},
    {"text": "Amazing customer service. Resolved my issue quickly.", "label": "Positive"},
    {"text": "Not satisfied with the quality of the product. Disappointed.", "label": "Negative"},
    {"text": "The delivery was delayed, but the product is good.", "label": "Neutral"},
    {"text": "The worst service I've ever encountered. Never using again.", "label": "Negative"},
    {"text": "Impressed with the product's durability. Highly recommended.", "label": "Positive"},
    {"text": "Neutral experience. Average service and product.", "label": "Neutral"},
    {"text": "Avoid this service at all costs. Terrible experience.", "label": "Negative"},
    {"text": "The user interface needs improvement. Not user-friendly.", "label": "Negative"},
    {"text": "Very happy with the purchase. Excellent customer service.", "label": "Positive"},
    {"text": "Would not recommend this service to anyone. Disappointing.", "label": "Negative"},
    {"text": "Great value for the money. Happy with the purchase.", "label": "Positive"},
    {"text": "This company has the worst customer service. Avoid.", "label": "Negative"},
    {"text": "Fast shipping and great product quality.", "label": "Positive"},
    {"text": "Okay service. Nothing exceptional.", "label": "Neutral"},
    {"text": "Product arrived damaged. Terrible experience.", "label": "Negative"},
    {"text": "Absolutely delighted with the service. Highly recommended.", "label": "Positive"},
    {"text": "Regret buying this product. Poor quality.", "label": "Negative"},
    {"text": "The support team was unhelpful. Disappointed.", "label": "Negative"},
    {"text": "Highly satisfied with the quality. Would buy again.", "label": "Positive"},
    {"text": "Not impressed with the customer service. No resolution.", "label": "Negative"},
    {"text": "The product met my expectations. Good value for money.", "label": "Positive"},
    {"text": "Service was a complete letdown. Will not use again.", "label": "Negative"},
    {"text": "Positive experience overall. Happy with the purchase.", "label": "Positive"},
    {"text": "Avoid this company. Terrible service and products.", "label": "Negative"},
    {"text": "Extremely disappointed with the quality. Regretful purchase.", "label": "Negative"},
    {"text": "Excellent customer service. Quick response and resolution.", "label": "Positive"},
    {"text": "Average experience with the product. Nothing outstanding.", "label": "Neutral"},
    {"text": "Negative experience with this service. Poor communication.", "label": "Negative"},
    {"text": "Very pleased with the purchase. Great value for money.", "label": "Positive"},
    {"text": "Avoid at all costs. Terrible customer service and product.", "label": "Negative"},
    {"text": "Impressed with the fast delivery. Good product quality.", "label": "Positive"},
    {"text": "Okay service, but the product didn't meet expectations.", "label": "Neutral"},
    {"text": "The worst purchase I've ever made. Complete disappointment.", "label": "Negative"},
    {"text": "Happy with the product. Would recommend to others.", "label": "Positive"},
    {"text": "Unsatisfied with the service. Will not use again.", "label": "Negative"},
    {"text": "This company is a scam. Avoid at all costs.", "label": "Negative"},
    {"text": "Impressed with the level of customer.", "label": "Neutral"}
]

# Convert the data to a Pandas DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('comments_with_labels.csv', index=False)
